name: Deploy Website

on:
  push:
    branches: [ main, master ]  # Runs on push to main or master branch
  workflow_dispatch:            # Allows manual trigger from GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build website
        run: npm run build
      
      - name: Create deployment directory
        run: |
          mkdir -p _site
          # Copy all necessary files to the deployment directory
          cp -r index.html _site/
          cp -r dist _site/
          cp -r img _site/
          cp CNAME _site/
          # Add any other static files or directories that need to be deployed
          # cp -r other-files _site/ (if needed)
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site       # The folder containing your complete website
          branch: gh-pages    # The branch to deploy to
          # No need to specify CNAME as we're including it in the _site directory